services:
  node:
    build: ./node
    image: my-node:vc1
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
  prom:
    build: ./prom
    image: my-prom:vc1
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: Prom/prometheus.yml
        target: /usr/local/prometheus-3.6.0-rc.0.linux-amd64/prometheus.yml
      - type: bind
        source: Prom/query.log
        target: /usr/local/prometheus-3.6.0-rc.0.linux-amd64/query.log
  graf:
    build: ./graf
    image: my-graf:vc1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: graf/datasources.yml
        target: /usr/local/grafana-12.1.1/conf/provisioning/datasources/datasources.yml

