server:
http_listen_address: ${PROMTAIL_CONTAINER_NAME}
http_listen_port: ${PROMTAIL_PORT}

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://${LOKI_CONTAINER_NAME}:${LOKI_PORT}/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
      - localhost

      labels:
        job: varlogs
        __path__: /var/log/*log

