global:
  scrape_interval: 15s
  evaluation_interval: 15s
  query_log_file: /usr/local/prometheus-3.6.0-rc.0.linux-amd64

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['my-node:9100']