apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_CONTAINER_NAME}:${PROMETHEUS_PORT}
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://${LOKI_CONTAINER_NAME}:${LOKI_PORT}
    jsonData:
      timeout: 60
      maxLines: 1000