global:
  scrape_interval: 15s
  evaluation_interval: 15s
  query_log_file: /prometheus/query.log

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['node:9100']