apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prom:9100
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://l-c:3100
    jsonData:
      timeout: 60
      maxLines: 1000